version: '3'
services:

  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      # persist data even if container shuts down
      - db:/var/lib/postgresql/data/
    networks:
      - shieldwall

  frontend-v3:
    container_name: frontcloud_frontend_v3
    build:
      context: ./frontend-v3
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./frontend-v3:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8666/api
      - CHOKIDAR_USEPOLLING=true
    networks:
      - shieldwall
    command: npm run dev

#  shieldwall_api:
#    container_name: shieldwall_api
#    image: shieldwall_api:latest
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    depends_on:
#      - database
#    ports:
#      - 8666:8666
#    volumes:
#      - ./api.yaml:/etc/shieldwall/config.yaml
#    restart: unless-stopped
#    networks:
#      - shieldwall

volumes:
  db:
  data:

networks:
  shieldwall:
    driver: bridge